#!/bin/bash
#PBS -l nodes=2:ppn=16,walltime=01:00:00
#PBS -N BoidSimMPI

# Define the working directory
export MYDIR="/newhome/ag17009/BoidSimulator"
# cd into working directory
cd $PBS_O_WORKDIR

#-------------------------------------------------
# Don’t change anything below this line
#-------------------------------------------------

export JOBNO="`echo $PBS_JOBID | sed s/.master.cm.cluster//`"
export CONF="$MYDIR/machines.$JOBNO"
for i in `cat $PBS_NODEFILE | uniq`;
do echo $i >> $CONF
done
export numnodes=`cat $CONF|wc -l`

#-------------------------------------------------
# Executions
# mpirun --machinefile $CONF -np $numnodes ./BoidSim <PPN> <Num_Boids>
# Do not set PPN above what has been requested.
#-------------------------------------------------

make build_mpi
mpirun -machinefile $CONF -np $numnodes ./BoidSim 16 5000